
services:
  recipe-api:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./recipe:/app
    working_dir: /app 
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
